FROM rieseberglab/analytics:1
LABEL maintainer="Jean-Sebastien Legare <jslegare@cs.ubc.ca>"

#fixups on permissions

RUN chmod o+rx \
    /home/ngm/ngm \
    /home/ngm/ngm-debug \
    /home/ngm/ngm-log
